# Generated by Django 4.2.8 on 2024-01-01 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherserializer',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='weatherserializer',
            name='sunrise',
            field=models.TimeField(default=datetime.time(12, 34, 56, 887470)),
        ),
        migrations.AddField(
            model_name='weatherserializer',
            name='sunset',
            field=models.TimeField(default=datetime.time(12, 34, 56, 887470)),
        ),
        migrations.AddField(
            model_name='weatherserializer',
            name='today',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
        migrations.AddField(
            model_name='weatherserializer',
            name='visibility',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='weatherserializer',
            name='weather',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='weatherserializer',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherserializer',
            name='precipitation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherserializer',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherserializer',
            name='wind_speed',
            field=models.FloatField(default=0),
        ),
    ]
