# Generated by Django 4.2.8 on 2024-01-01 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_weatherserializer_name_weatherserializer_sunrise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherserializer',
            name='sunrise',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weatherserializer',
            name='sunset',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weatherserializer',
            name='today',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
