# Generated by Django 4.2.8 on 2024-01-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_alter_weatherserializer_sunrise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherserializer',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
