# Generated by Django 4.2.8 on 2024-01-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0005_alter_weatherserializer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherserializer',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
